### ISSUE TITLE
有一个单词写错了

### ISSUE THREAD

**Issue by MmingY** [mainlxl/ffmpeg-build#1]
您好，您有一个单词写错了哈~`TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/darwin-x86_64`这句的应该是`linux-x86_64`哈~
完整的是`TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64`

**Comment by fr1014** [comment]
mac上的路径是darwin，分系统的

**Comment by mainlxl** [comment]
你好我这个是在mac上编译的 使用的darwin
